name: publish hibit-id-sdk packages to npm
on:
  release:
    types: [published]
  push:
    branches:
      - main
jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          cache: yarn
      - run: |
          npm config set ${REGISTRY}:_authToken ${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set @delandlabs:registry https:${REGISTRY}
        env:
          REGISTRY: //registry.npmjs.org/
      - run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            Version=$(git describe --tags --abbrev=0)
          else
            Version=1.1.0-alpha.$(date +"%Y%m%d%H%M%S")
          fi
          echo Version: $Version
          export VITE_RELEASE_VERSION=$Version

          yarn install --frozen-lockfile

          # Replace * with actual version in package.json
          node scripts/replaceVersions.js $Version

          yarn build:all

          yarn publish --frozen-lockfile --non-interactive --no-git-tag-version --no-commit-hooks --new-version ${Version} packages/crypto-lib --access public
          yarn publish --frozen-lockfile --non-interactive --no-git-tag-version --no-commit-hooks --new-version ${Version} packages/coin-base --access public
          yarn publish --frozen-lockfile --non-interactive --no-git-tag-version --no-commit-hooks --new-version ${Version} packages/coin-dfinity --access public
          yarn publish --frozen-lockfile --non-interactive --no-git-tag-version --no-commit-hooks --new-version ${Version} packages/coin-ethereum --access public
          yarn publish --frozen-lockfile --non-interactive --no-git-tag-version --no-commit-hooks --new-version ${Version} packages/coin-kaspa --access public
          yarn publish --frozen-lockfile --non-interactive --no-git-tag-version --no-commit-hooks --new-version ${Version} packages/coin-solana --access public
          yarn publish --frozen-lockfile --non-interactive --no-git-tag-version --no-commit-hooks --new-version ${Version} packages/coin-ton --access public
          yarn publish --frozen-lockfile --non-interactive --no-git-tag-version --no-commit-hooks --new-version ${Version} packages/coin-tron --access public
          yarn publish --frozen-lockfile --non-interactive --no-git-tag-version --no-commit-hooks --new-version ${Version} packages/sdk --access public
