name: Run Tests

on:
  push:
    branches:
      - release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build:all

      - name: Run tests
        run: yarn test:all
